// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR7XTAAGDzpcoipEb6NJUqIpEtnF6WdhM',
    appId: '1:840373899081:web:e3d1877f49017427e99498',
    messagingSenderId: '840373899081',
    projectId: 'tasky-app-64eaa',
    authDomain: 'tasky-app-64eaa.firebaseapp.com',
    storageBucket: 'tasky-app-64eaa.firebasestorage.app',
    measurementId: 'G-TTWVR57BJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFS7RjMGJhkIh2APFsmxV3zAT2TQmE9u0',
    appId: '1:840373899081:android:4c33cfd37e699154e99498',
    messagingSenderId: '840373899081',
    projectId: 'tasky-app-64eaa',
    storageBucket: 'tasky-app-64eaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACv-HDgZkz33fu0QvH1Y-TwnOTdMzjA2E',
    appId: '1:840373899081:ios:13529f6c1d35c90fe99498',
    messagingSenderId: '840373899081',
    projectId: 'tasky-app-64eaa',
    storageBucket: 'tasky-app-64eaa.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACv-HDgZkz33fu0QvH1Y-TwnOTdMzjA2E',
    appId: '1:840373899081:ios:13529f6c1d35c90fe99498',
    messagingSenderId: '840373899081',
    projectId: 'tasky-app-64eaa',
    storageBucket: 'tasky-app-64eaa.firebasestorage.app',
    iosBundleId: 'com.example.taskyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR7XTAAGDzpcoipEb6NJUqIpEtnF6WdhM',
    appId: '1:840373899081:web:4f4eab518f21b0c3e99498',
    messagingSenderId: '840373899081',
    projectId: 'tasky-app-64eaa',
    authDomain: 'tasky-app-64eaa.firebaseapp.com',
    storageBucket: 'tasky-app-64eaa.firebasestorage.app',
    measurementId: 'G-SE89S8Z85S',
  );

}